version: '3'

services:
  web:
    build: ./  # Path to the directory containing the Flask app's Dockerfile
    ports:
      - "5000:5000"  # Expose port 5000 on the host for Flask app
    depends_on:
      - mongo_db  # Depend on the mongo_db service

  mongo_db:
    image: mongo:latest  # Use the latest MongoDB image from Docker Hub
    volumes:
      - ./data/db:/data/db  # Mount a local volume to store MongoDB data
    ports:
      - "27017:27017"  # Expose port 27017 on the host for MongoDB